# Site configuration
timezone: America/New_York
title: Lyften
url: http://localhost:8080
target: /public

# Pagination
max_per_page: 15

# Files extensions to exclude when copying static files
exclude: [swp, bak, DS_Store, gitkeep]

# Folders and files to copy
copy: [favicon.png, uploads, skosh.php, skosh, .htaccess]