# Site configuration
timezone: America/New_York
title: Lyften
url: http://lyften.local:8888
target: /public

# Pagination
max_per_page: 15

# Files extensions to exclude when copying static files
exclude: [swp, bak, DS_Store, gitkeep, vendor]

# Folders and files to copy
copy: [uploads, skosh.php, skosh, .htaccess]

twig_extensions: ['\App\TwigExtension\Metadata']

# Register custom events
#events:
#  builder.booted: ['\App\Events\TwigProvider']