# Site configuration
timezone: America/New_York
title: Lyften
url: http://localhost:8080
target: /public
url_trailing_slash: true
date_format: F m, Y

# Pagination
max_per_page: 15

# Files extensions to exclude when copying static files
exclude: [swp, bak, DS_Store, gitkeep, vendor]

# Folders and files to copy
copy: [uploads, skosh.php, skosh, .htaccess]

# Register twig extensions
twig_extensions: ['\App\TwigExtension\Metadata']

# Register custom events
#events:
#  paginate.before: ['\App\Events\Tester']